apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-monitor
  name: pod-monitor
  namespace: flux-system
spec:
  containers:
  - image: nginx
    name: pod-monitor
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
