name: Infrastructure Pipeline

on:
  push:
    branches:
        - main

jobs:
  infrastructure:
    name: Create Cloud Infrastructure
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    defaults:
      run:
        working-directory: ./environments/dev
    env:
      TF_VAR_identity_private_key: ${{ secrets.IDENTITY_PRIVATE_KEY }}
      TF_VAR_identity_public_key: ${{ secrets.IDENTITY_PUBLIC_KEY }}
      TF_VAR_known_hosts: ${{ secrets.KNOWN_HOSTS }}


    steps:
    - name: Create Repository
      uses: actions/checkout@v4

    # - name: Access AWS
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}

    # - name: Dump OIDC token claims
    #   shell: bash
    #   run: |
    #     echo "Requesting OIDC token..."

    #     TOKEN=$(curl -s \
    #       -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
    #       "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r '.value')

    #     echo "Token received." 

    #     echo "$TOKEN" | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .
    - name: Debug GitHub identity
      run: |
        echo "Role: ${{ vars.AWS_ROLE_TO_ASSUME }}"
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"
        echo "Workflow: ${{ github.workflow }}"

    - name: Access AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          # FIX: Add this line so GitHub knows where to point the deployment.
        aws-region: us-east-1  

    - name: Establish Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.6.2
        terraform_wrapper: false

    - name: Verify Terraform Code Syntax
      run: terraform init && terraform validate

    - name: Deploy Code into Infrastructure
      env:
        TF_VAR_github_token: ${{ secrets.MY_GITHUB_PAT }}
      run: terraform apply -auto-approve
    #  run: terraform apply -target=module.github-actions -target=module.vpc -target=module.ecr -target=module.eks -auto-approve
       
    # - name: Push Remaining IRSA
    #   run: terraform apply -target=module.irsa -auto-approve

    # - name: Push Remaining Secret
    #   run: terraform apply -target=module.flux -auto-approve