name: Infrastructure Pipeline

on:
  push:
    branches:
        - main

jobs:
  infrastructure:
    name: Create Cloud Infrastructure 
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    defaults:
      run:
        working-directory: ./environments/dev/platform
    env:
      TF_VAR_identity_private_key: ${{ secrets.FLUX_IDENTITY_PRIVATE_KEY }}
      TF_VAR_identity_public_key: ${{ secrets.FLUX_IDENTITY_PUBLIC_KEY }}
      TF_VAR_known_hosts: ${{ secrets.FLUX_KNOWN_HOSTS }}
     # TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
      TF_VAR_github_token: ${{ secrets.MY_GITHUB_PAT }}


    steps:
    - name: Create Repository
      uses: actions/checkout@v4

 

    - name: Access AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1  


    


    - name: Establish Terraform   
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.6.2
        terraform_wrapper: false
    - name: Verify Terraform Code Syntax
      run: terraform init -upgrade && terraform validate

  
    - name: Check Flux variable lengths
      shell: bash
      run: |
        echo "private key length: ${#TF_VAR_identity_private_key}"
        echo "public key length: ${#TF_VAR_identity_public_key}"
        echo "known_hosts length: ${#TF_VAR_known_hosts}"

    #- name: Terraform Plan
      #run: terraform plan -replace='module.flux.kubernetes_secret_v1.flux-git-deploy'

    - name: Deploy Code into InfraS
      # env:
      #   TF_VAR_github_token: ${{ secrets.MY_GITHUB_PAT }}
      run: terraform plan
    
    - name: Apply Code into InfraS
      run: terraform apply -auto-approve
     # run: terraform apply -target=module.github-actions -target=module.vpc -target=module.ecr -target=module.eks -auto-approve
       
    # - name: Push Remaining IRSA
    #   run: terraform apply -target=module.irsa -auto-approve

    # - name: Push Remaining Secret
    #   run: terraform apply -target=module.flux -auto-approve